image:
  file: .gitpod.Dockerfile

tasks:
  - name: Open chromium browser
    command: chromium

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
